Repository foyer-rs/foyer, pull requests merged in 2023-07, with the labels that each got.

#32 feat: impl storage recovery
  Cargo.lock
  foyer-storage-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/device/fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/store.rs
Labels: enhancement

#35 feat: introduce segment fifo eviction policy
  foyer-intrusive/src/core/adapter.rs
  foyer-intrusive/src/eviction/fifo.rs
  foyer-intrusive/src/eviction/lfu.rs
  foyer-intrusive/src/eviction/lru.rs
  foyer-intrusive/src/eviction/mod.rs
  foyer-storage/src/lib.rs
Labels: enhancement

#37 feat: export mods
  Cargo.lock
  foyer/Cargo.toml
  foyer/src/lib.rs
Labels: chore

#38 fix: export extern crate
  foyer/src/lib.rs
Labels: chore

#39 Revert "fix: export extern crate"
  foyer/src/lib.rs
Labels: chore

#40 fix: disable O_DIRECT on non-linux targets
  foyer-storage/src/device/fs.rs
Labels: bug

#46 chore: ignore Cargo.lock and bump toolchain
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .gitignore
  Cargo.lock
  rust-toolchain
Labels: chore

#50 chore: export storage config
  foyer-storage/src/lib.rs
Labels: chore

#51 chore: AdmitAll & ReinsertNone no longer requires KV default
  foyer-storage/src/admission.rs
  foyer-storage/src/reinsertion.rs
Labels: chore

#53 fix: region advance & recovery & seal
  foyer-intrusive/src/eviction/fifo.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/store.rs
Labels: bug

#54 feat: introduce prometheus metrics
  foyer-storage-bench/src/main.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/metrics.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/store.rs
Labels: enhancement

#55 fix: recovery test
  foyer-storage/src/store.rs
Labels: bug

#56 feat: support multiple admission or reinsertion policies, loose lock
  foyer-storage-bench/src/main.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/reinsertion.rs
  foyer-storage/src/store.rs
Labels: enhancement

#57 feat: introduce rated random admission policy
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-common/src/code.rs
  foyer-intrusive/src/core/adapter.rs
  foyer-storage/src/admission/all.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_random.rs
  foyer-storage/src/store.rs
Labels: enhancement

#58 feat: add rated random option for bench args
  foyer-storage-bench/src/main.rs
  foyer-storage/src/admission/all.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/reinsertion.rs
  foyer-storage/src/store.rs
Labels: enhancement

#59 fix: recovery run flushers and reclaimers first
  foyer-storage/src/store.rs
Labels: bug

#60 chore: remove old metrics, reclaim drop indices first
  foyer-storage/src/reclaimer.rs
  foyer/src/lib.rs
  foyer/src/metrics.rs
Labels: chore

#62 fix: raise error in bench metrics instead of panic
  foyer-storage-bench/src/main.rs
Labels: bug

#63 feat: introduce intrusive hashmap
  foyer-common/src/code.rs
  foyer-intrusive/src/collections/hashmap.rs
  foyer-intrusive/src/collections/mod.rs
  foyer-intrusive/src/core/adapter.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/region_manager.rs
Labels: enhancement

#64 feat: introduce basic memory cache framework
  Cargo.toml
  foyer-common/src/code.rs
  foyer-intrusive/src/collections/hashmap.rs
  foyer-intrusive/src/eviction/fifo.rs
  foyer-intrusive/src/eviction/lfu.rs
  foyer-intrusive/src/eviction/lru.rs
  foyer-intrusive/src/eviction/mod.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/lib.rs
Labels: enhancement

#65 feat: sleep 10ms while trying to acquire exclusive lock
  foyer-storage/src/admission/rated_random.rs
  foyer-storage/src/region.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/store.rs
Labels: enhancement

#68 feat: introduce thread-safe rate limiter
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-common/Cargo.toml
  foyer-common/src/code.rs
  foyer-common/src/lib.rs
  foyer-common/src/rate.rs
  foyer-storage-bench/src/utils.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/device/fs.rs
  rustfmt.toml
Labels: enhancement

#70 feat: introduce flush & reclaim rate limit
  foyer-storage-bench/src/main.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/store.rs
Labels: enhancement

#71 feat: introduce intrusive duplicated hashmap
  foyer-intrusive/src/collections/dlist.rs
  foyer-intrusive/src/collections/duplicated_hashmap.rs
  foyer-intrusive/src/collections/mod.rs
Labels: enhancement

#72 feat: add prometheus namespace config
  foyer-storage-bench/src/main.rs
  foyer-storage/src/indices.rs
  foyer-storage/src/metrics.rs
  foyer-storage/src/store.rs
Labels: enhancement

#74 feat: introduce event listener
  foyer-storage-bench/src/main.rs
  foyer-storage/src/error.rs
  foyer-storage/src/event.rs
  foyer-storage/src/indices.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/store.rs
Labels: enhancement

#75 feat: introduce store writer
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_random.rs
  foyer-storage/src/metrics.rs
  foyer-storage/src/store.rs
Labels: enhancement

#76 fix: writer weight calculate
  foyer-storage/src/store.rs
Labels: bug

#77 feat: refactor admission policy interface, fix rated random with multiple policies
  foyer-storage-bench/src/utils.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_random.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/metrics.rs
  foyer-storage/src/store.rs
Labels: bug, enhancement

#78 feat: add more insert interfaces
  foyer-storage/src/store.rs
Labels: enhancement

#79 refactor: insert with interface allow return fetch value error
  foyer-storage/Cargo.toml
  foyer-storage/src/error.rs
  foyer-storage/src/store.rs
Labels: enhancement

#80 fix: refactor future interface in insert with
  foyer-storage/src/metrics.rs
  foyer-storage/src/store.rs
Labels: enhancement

#81 fix: reverse condition of insert if not exists
  foyer-storage/src/store.rs
Labels: bug

#82 fix: remove mistake cfg attr
  foyer-storage/src/device/mod.rs
Labels: bug, chore

#83 fix: make slice drop recoverable
  foyer-storage/src/region.rs
Labels: bug

#87 chore: add makefile for check and test
  Makefile
Labels: chore

#88 chore: add README and pr template
  .github/pull_request_template.md
  README.md
Labels: chore

#86 feat: implement async queue with notify
  foyer-common/Cargo.toml
  foyer-common/src/queue.rs
Labels: enhancement

#90 feat: impl poll mode flushers and reclaimers instead of push mode
  foyer-common/src/queue.rs
  foyer-common/src/rate.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/event.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/store.rs
Labels: enhancement

#91 fix: resolve reinsertion stack by modify allocation
  foyer-common/src/batch.rs
  foyer-common/src/lib.rs
  foyer-common/src/queue.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/store.rs
Labels: bug, enhancement

#93 refactor: modify shutdown runners order, add hakari check
  .config/hakari.toml
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Cargo.toml
  Makefile
  README.md
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage-bench/src/analyze.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/store.rs
  foyer-workspace-hack/.gitattributes
  foyer-workspace-hack/Cargo.toml
  foyer-workspace-hack/build.rs
  foyer-workspace-hack/src/lib.rs
  foyer/Cargo.toml
Labels: enhancement
