Repository foyer-rs/foyer, pull requests merged in 2024-08, with the labels that each got.

#625 refactor: fix warnings for toolchain 1.80
  foyer-common/Cargo.toml
  foyer-common/src/lib.rs
  foyer-memory/src/indexer/sanity.rs
  foyer-storage/src/serde.rs
  foyer-util/src/lib.rs
Labels: refactor

#624 perf: reduce page fault when writing disk cache io buffer
  foyer-storage/src/device/bytes.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
Labels: perf

#626 refactor: tiny refine batch code
  foyer-storage/src/large/batch.rs
Labels: refactor

#627 refactor: refine batch buffer pool by IoBufferPool
  foyer-storage/src/io_buffer_pool.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/lib.rs
Labels: refactor

#632 refactor: refine storage trait, use hash instead of key
  foyer-memory/src/cache.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
Labels: refactor

#633 refactor: move key comparison into foyer-storage
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/hybrid/cache.rs
Labels: refactor

#634 fix: fix wait impl
  foyer-storage/src/engine.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/cache.rs
Labels: bug, refactor

#635 refactor: remove write handle for enqueue and delete
  foyer-storage/src/engine.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/hybrid/cache.rs
  foyer/src/hybrid/writer.rs
  foyer/src/prelude.rs
Labels: refactor

#637 refactor: remove runtime storage, always use dedicated runtime
  examples/hybrid_full.rs
  foyer-bench/src/main.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/prelude.rs
Labels: refactor

#638 fix: fix panic with none recover mode
  foyer-storage/src/large/recover.rs
Labels: bug

#639 fix: fix panic with none recover mode (#638)
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#640 cherry-pick fix: fix panic with none recover mode (#638 #639)
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-storage/src/large/recover.rs
  foyer/Cargo.toml
Labels: bug

#641 feat: add serde support for recover mode
  foyer-storage/src/large/recover.rs
Labels: feature

#642 chore: release foyer 0.10.3
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#643 cherry-pick: feat: add serde support for recover mode (#641 #642)
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-storage/src/large/recover.rs
  foyer/Cargo.toml
Labels: feature

#644 feat: support customize runtime max blocking threads
  examples/hybrid_full.rs
  foyer-bench/src/main.rs
  foyer-storage/src/store.rs
Labels: feature

#646 feat: support raw block device with DirectFile
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Cargo.toml
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/compress.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/serde.rs
Labels: feature

#647 fix: fix foyer-bench recover mode
  foyer-bench/src/main.rs
Labels: bug

#648 feat: support set foyer-bench worker threads
  foyer-bench/src/main.rs
Labels: feature

#649 perf: add O_NOATIME on linux
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
Labels: perf

#650 chore: upgrade deps
  Cargo.toml
  examples/Cargo.toml
  foyer-bench/Cargo.toml
  foyer-memory/Cargo.toml
Labels: chore, dependencies

#655 pref: reduce lfu cmsketch page fault
  foyer-bench/src/main.rs
  foyer-memory/Cargo.toml
Labels: perf

#656 perf: reduce store clone overhead
  foyer-storage/src/store.rs
Labels: perf

#657 chore: fix license header
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/io_buffer_pool.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/small/generic.rs
Labels: chore

#659 doc: update readme
  CHANGELOG.md
  README.md
  examples/Cargo.toml
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-util/Cargo.toml
  foyer/Cargo.toml
Labels: documentation, chore

#661 feat: support serde for more configs
  foyer-common/src/tracing.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/store.rs
Labels: feature

#662 refactor: expose Weighter trait
  foyer/src/prelude.rs
Labels: refactor

#663 chore: release foyer 0.11.0
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  CHANGELOG.md
  README.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#666 feat: introduce metrics for serde
  etc/grafana/dashboards/foyer.json
  foyer-bench/Cargo.toml
  foyer-common/src/metrics.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
Labels: feature

#667 chore: fmt code with unstable fmt features
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  foyer-bench/src/main.rs
  foyer-common/src/fs.rs
  foyer-common/src/future.rs
  foyer-common/src/tracing.rs
  foyer-common/src/wait_group.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/sanity.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/handle.rs
  foyer-memory/src/indexer/hash_table.rs
  foyer-memory/src/indexer/sanity.rs
  foyer-memory/src/prelude.rs
  foyer-storage/src/device/bytes.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/large/serde.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/picker/mod.rs
  foyer-storage/src/picker/utils.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/cache.rs
  foyer/src/hybrid/writer.rs
  foyer/src/prelude.rs
  rustfmt.nightly.toml
  rustfmt.toml
Labels: chore

#670 chore: fix spelling errors in comments
  foyer-memory/src/lib.rs
Labels: chore

#671 chore: fix more typos
  CHANGELOG.md
  foyer/src/hybrid/builder.rs
Labels: chore

#668 perf: refine `fetch` runtime usage
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
Labels: refactor, perf

#672 feat: impl Default for TokioRuntimeConfig
  foyer-storage/src/store.rs
Labels: feature

#673 fix: fix build with madsim
  foyer-common/src/asyncify.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/store.rs
Labels: bug

#677 fix: fix panic on scanner overflow
  foyer-storage/src/error.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/region.rs
Labels: bug

#679 fix: hide unnecessary error on load error
  foyer-storage/src/compress.rs
  foyer-storage/src/error.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/serde.rs
Labels: bug

#680 chore: move compact bloom filter to utils, fix typos
  examples/tail_based_tracing.rs
  foyer-bench/src/main.rs
  foyer-common/Cargo.toml
  foyer-common/src/bits.rs
  foyer-common/src/lib.rs
  foyer-common/src/object_pool.rs
  foyer-common/src/range.rs
  foyer-common/src/wait_group.rs
  foyer-intrusive/src/adapter.rs
  foyer-memory/benches/bench_dynamic_dispatch.rs
  foyer-memory/src/context.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/handle.rs
  foyer-memory/src/lib.rs
  foyer-storage/src/compress.rs
  foyer-storage/src/device/bytes.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/picker/utils.rs
  foyer-storage/src/region.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
  foyer-util/Cargo.toml
  foyer-util/src/compact_bloom_filter.rs
  foyer-util/src/lib.rs
Labels: chore, refactor

#681 chore: release foyer 0.11.1
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore
