Repository foyer-rs/foyer, pull requests merged in 2024-09, with the labels that each got.

#684 fix: build on windows
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-common/Cargo.toml
  foyer-common/src/fs.rs
  foyer-common/src/lib.rs
  foyer-memory/Cargo.toml
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/large/generic.rs
  foyer-util/Cargo.toml
  foyer-util/src/iostat.rs
Labels: feature

#685 chore: move fs4 deps to foyer-storage
  foyer-common/Cargo.toml
  foyer-common/src/fs.rs
  foyer-common/src/lib.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
Labels: dependencies, refactor

#693 feat: introduce foyer-cli framework
  Cargo.toml
  codecov.yml
  foyer-cli/Cargo.toml
  foyer-cli/src/args/error.rs
  foyer-cli/src/args/fio.rs
  foyer-cli/src/args/mod.rs
  foyer-cli/src/main.rs
Labels: feature

#695 perf: introduce size hint for storage key and value
  foyer-common/src/code.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/store.rs
Labels: feature, perf

#696 revert: "perf: introduce size hint for storage ... (#695)"
  foyer-common/src/code.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/store.rs
Labels: refactor

#698 refactor: use bytesize for foyer-bench
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Cargo.toml
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
  foyer-cli/Cargo.toml
Labels: refactor

#702 fix: add `--locked` for `cargo-nextest` and `cargo-udeps`
  scripts/install-deps.sh
Labels: bug

#703 chore: refine ci
  .github/template/generate.sh
  .github/template/main-override.yml
  .github/template/pr-override.yml
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
Labels: test

#704 chore: fix ci badge in readme
  README.md
Labels: documentation, chore

#697 perf: use size hint on serde
  foyer-storage/Cargo.toml
  foyer-storage/src/serde.rs
  foyer-storage/src/store.rs
Labels: perf

#705 feat: expose in-memory cache builder and cache entry
  foyer/src/prelude.rs
Labels: feature

#706 chore: release foyer 0.11.2
  CHANGELOG.md
  README.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#711 doc: remove details tag in change log for better searching
  CHANGELOG.md
Labels: documentation, chore

#712 chore: add some metadata for changelog
  CHANGELOG.md
Labels: documentation, chore

#713 chore: ignore changelog author details
  CHANGELOG.md
Labels: documentation, chore

#719 chore: update readme, add website
  README.md
  foyer/src/lib.rs
Labels: documentation, chore

#721 chore: update badge with link
  README.md
  foyer/src/lib.rs
Labels: documentation, chore

#724 fix: fix io buffer pool alignment
  foyer-storage/src/io_buffer_pool.rs
  foyer-storage/src/large/batch.rs
Labels: bug

#725 chore: relase foyer 0.11.3
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#728 doc: fix a tiny broken link
  foyer-storage/src/device/direct_file.rs
Labels: documentation, chore

#729 refactor: rename with_buffer_threshold to with_buffer_pool_size
  examples/hybrid_full.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/builder.rs
Labels: refactor

#730 chore: warn if DirectFileDevice is used in a fs
  foyer-storage/src/device/direct_file.rs
Labels: feature

#717 refactor: revert the pre-serialization and parallel buffer
  examples/Cargo.toml
  foyer-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-storage/src/engine.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/store.rs
Labels: perf

#732 refactor: replace manual future enum with auto_enum
  foyer-storage/Cargo.toml
  foyer-storage/src/engine.rs
  foyer-storage/src/storage/either.rs
Labels: refactor

#733 chore: release foyer 0.11.4
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#736 fix: hold runtime ref and handle to prevent spawn after shutdown
  foyer-common/src/asyncify.rs
  foyer-common/src/runtime.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: bug, refactor

#737 chore: release foyer 0.11.5
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#739 chore: update license checker version
  .github/workflows/license_check.yml
Labels: chore

#658 feat: introduce small object disk cache
  .github/workflows/ci.yml
  examples/hybrid.rs
  examples/hybrid_full.rs
  examples/tail_based_tracing.rs
  foyer-bench/src/main.rs
  foyer-common/src/runtime.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/io_buffer_pool.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/picker/mod.rs
  foyer-storage/src/picker/utils.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/batch.rs
  foyer-storage/src/small/bloom_filter.rs
  foyer-storage/src/small/flusher.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/small/mod.rs
  foyer-storage/src/small/serde.rs
  foyer-storage/src/small/set.rs
  foyer-storage/src/small/set_manager.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: feature, refactor, test

#744 feat: impl destroy for sodc
  foyer-storage/Cargo.toml
  foyer-storage/src/small/batch.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/small/set.rs
  foyer-storage/src/small/set_manager.rs
Labels: feature, refactor

#745 refactor: refine device build
  examples/hybrid.rs
  examples/hybrid_full.rs
  examples/tail_based_tracing.rs
  foyer-bench/src/main.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: refactor

#749 feat: introduce submit queue size threshold
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/store.rs
Labels: feature

#750 bug: fix panic when serde as batching
  foyer-storage/src/large/batch.rs
Labels: bug
