Repository foyer-rs/foyer, pull requests merged in 2024-06, with the labels that each got.

#551 perf: support jemalloc for foyer bench
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
Labels: perf

#552 feat: introduce new event listener abstraction
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  examples/Cargo.toml
  examples/event_listener.rs
  foyer-common/src/event.rs
  foyer-common/src/lib.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer/src/hybrid/builder.rs
  foyer/src/prelude.rs
Labels: feature

#553 chore: release foyer 0.9.2
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#554 fix: use libc::O_DIRECT for multi target/os/arch
  foyer-storage/Cargo.toml
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
Labels: bug

#556 chore: release foyer-storage 0.8.3
  CHANGELOG.md
  foyer-storage/Cargo.toml
Labels: chore

#557 perf: use dedicated runtime to fetch with hybrid cache
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store/mod.rs
  foyer-storage/src/store/noop.rs
  foyer-storage/src/store/runtime.rs
  foyer/src/hybrid/cache.rs
Labels: perf

#558 chore: release foyer v0.9.3
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#563 fix: fix phantom entry after recovery by check sequence
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/tests/storage_test.rs
Labels: bug

#560 fix: fix hyrbid cache metrics hit on in-memory cache hit
  foyer/src/hybrid/cache.rs
Labels: bug

#564 chore: release foyer 0.9.4
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#569 chore: remove binstall on CI
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
Labels: chore

#568 typo: typo spell `admission_picker`
  foyer-storage/src/store/mod.rs
Labels: chore

#567 perf: impl tail-based tracing with minitrace
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .gitignore
  Cargo.toml
  Makefile
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
  foyer-common/src/lib.rs
  foyer-common/src/trace.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/store/mod.rs
  foyer/Cargo.toml
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: perf

#571 perf: upgrade minitrace to reduce overhead
  Cargo.toml
Labels: perf

#572 chore: add logo for foyer
  etc/logo/brand.min.svg
  etc/logo/brand.svg
  etc/logo/logo.min.svg
  etc/logo/logo.svg
  etc/logo/slogan.min.svg
  etc/logo/slogan.svg
Labels: documentation, chore

#573 chore: update readme
  README.md
Labels: documentation, chore

#574 perf: add runtime switch to enable/disable tracing
  foyer-bench/src/main.rs
  foyer/src/hybrid/cache.rs
Labels: perf

#575 chore: switch minitrace to crates.io version
  Cargo.toml
  foyer-bench/src/main.rs
Labels: chore

#576 perf: add more minitrace spans
  foyer-common/Cargo.toml
  foyer-common/src/trace.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/indexer.rs
  foyer-storage/src/store/mod.rs
  foyer/Cargo.toml
  foyer/src/hybrid/cache.rs
Labels: perf

#583 fix: fix hybrid cache fetch span
  foyer/src/hybrid/cache.rs
Labels: bug, perf

#584 refactor: refine tracing spans
  foyer-memory/src/generic.rs
  foyer/src/hybrid/cache.rs
Labels: refactor, perf

#586 fix: fix fetch() trace span
  foyer-common/src/metrics.rs
  foyer-common/src/trace.rs
  foyer-memory/src/generic.rs
  foyer/src/hybrid/cache.rs
Labels: bug, perf

#587 bench: replace obtain with fetch for foyer bench
  foyer-bench/src/main.rs
Labels: refactor, test, perf

#588 fix: fix foyer bench get miss metrics
  foyer-bench/src/main.rs
Labels: bug
