Repository foyer-rs/foyer, pull requests merged in 2024-04, with the labels that each got.

#303 feat: add S3Fifo eviction for memory
  foyer-intrusive/src/core/adapter.rs
  foyer-intrusive/src/eviction/lfu.rs
  foyer-intrusive/src/lib.rs
  foyer-memory/Cargo.toml
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/prelude.rs
  foyer-workspace-hack/Cargo.toml
Labels: feature

#307 chore: bump foyer-intrusive to 0.3.1, foyer-memory to 0.1.3
  CHANGELOG.md
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
Labels: chore

#309 chore: bump foyer-storage to 0.5.1
  CHANGELOG.md
  foyer-storage/Cargo.toml
Labels: chore

#312 fix: fix state() for s3fifo
  foyer-memory/src/cache.rs
  foyer-memory/src/lib.rs
Labels: bug

#313 chore: bump foyer-memory to 0.1.4
  CHANGELOG.md
  foyer-memory/Cargo.toml
Labels: chore

#314 refactor: use generic type for cursor instead of associated type
  foyer-common/src/code.rs
  foyer-common/src/lib.rs
  foyer-intrusive/src/lib.rs
  foyer-storage/src/lib.rs
Labels: refactor

#315 refactor: remove unstable feature let_chains and lint_reasons
  foyer-common/src/code.rs
  foyer-common/src/lib.rs
  foyer-experimental/src/lib.rs
  foyer-intrusive/src/lib.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/eviction/test_utils.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/lib.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/region.rs
  foyer-storage/src/reinsertion/mod.rs
  foyer-storage/src/test_utils.rs
  foyer-storage/tests/storage_test.rs
Labels: refactor

#316 refactor: remove usage of unstable features
  foyer-common/Cargo.toml
  foyer-common/src/bits.rs
  foyer-common/src/code.rs
  foyer-common/src/lib.rs
  foyer-common/src/range.rs
  foyer-experimental/Cargo.toml
  foyer-experimental/src/error.rs
  foyer-experimental/src/lib.rs
  foyer-experimental/src/metrics.rs
  foyer-experimental/src/wal.rs
  foyer-intrusive/src/eviction/mod.rs
  foyer-intrusive/src/lib.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/allocator.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/metrics.rs
  foyer-storage/src/storage.rs
  foyer/src/lib.rs
Labels: refactor

#317 refactor: use crate allocator_api2 to make foyer build on stable
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  foyer-common/src/lib.rs
  foyer-experimental/src/wal.rs
  foyer-intrusive/src/core/adapter.rs
  foyer-intrusive/src/lib.rs
  foyer-memory/src/lib.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/allocator.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/region.rs
  foyer-workspace-hack/Cargo.toml
  rust-toolchain
  rustfmt.toml
Labels: refactor

#318 test: run CI on both linux and macos
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-experimental-bench/src/utils.rs
  foyer-storage-bench/src/utils.rs
  foyer-storage/src/device/fs.rs
Labels: test

#319 doc: update README and add a simple example
  .config/hakari.toml
  Cargo.toml
  README.md
  examples/Cargo.toml
  examples/memory.rs
  foyer-common/Cargo.toml
  foyer-experimental-bench/Cargo.toml
  foyer-experimental/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-workspace-hack/Cargo.toml
  foyer/Cargo.toml
Labels: documentation

#321 chore: add msrv for foyer, update bager in readme
  README.md
  foyer/Cargo.toml
Labels: documentation, chore

#322 fix: do not truncate when open wal
  foyer-experimental/src/wal.rs
Labels: bug

#324 refactor: loose query key bound for in-memory cache
  examples/memory.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/indexer.rs
Labels: refactor

#326 perf: add dynamic dispatch bench
  foyer-memory/Cargo.toml
  foyer-memory/benches/bench_dynamic_dispatch.rs
Labels: chore

#331 chore: fix ci coverage
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-memory/Cargo.toml
Labels: bug, chore, test

#334 refactor: loose bound of in-memory eviction related traits
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/fifo.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/lru.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/eviction/test_utils.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/handle.rs
  foyer-memory/src/indexer.rs
Labels: refactor

#335 test: upload binaries when asan/lsan test fails
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
Labels: chore, test

#340 fix: fix error convertion stack overflow
  foyer-experimental/src/error.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/error.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/error.rs
  foyer-storage/src/flusher.rs
  foyer-workspace-hack/Cargo.toml
Labels: bug

#341 feat: introduce eviction queue abstraction
  foyer-memory/src/eviction/fifo.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/lru.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/eviction/queue.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/eviction/test_utils.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/prelude.rs
Labels: feature

#342 chore: use codecov v4 with token
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
Labels: chore, test

#343 refactor: unify Key Value in foyer-common mod code
  foyer-common/src/buf.rs
  foyer-common/src/code.rs
  foyer-common/src/lib.rs
  foyer-experimental/src/wal.rs
  foyer-intrusive/src/collections/duplicated_hashmap.rs
  foyer-intrusive/src/collections/hashmap.rs
  foyer-intrusive/src/core/adapter.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/handle.rs
  foyer-memory/src/indexer.rs
  foyer-memory/src/lib.rs
  foyer-memory/src/listener.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_ticket.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/reinsertion/exist.rs
  foyer-storage/src/reinsertion/mod.rs
  foyer-storage/src/reinsertion/rated_ticket.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
Labels: refactor

#346 refactor: export unified eviction queue abstraction
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/lib.rs
  foyer-memory/src/prelude.rs
  foyer-memory/src/queue/generic.rs
  foyer-memory/src/queue/mod.rs
Labels: refactor

#347 feat: add `pop()` and `pop_corase()` interface for in-memory cache
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
Labels: feature

#348 refactor: use in-memory cache to refactor disk cache
  examples/memory.rs
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/fifo.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/lru.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/prelude.rs
  foyer-storage-bench/Cargo.toml
  foyer-storage-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
Labels: refactor

#349 refactor: remove unused components
  foyer-intrusive/src/collections/duplicated_hashmap.rs
  foyer-intrusive/src/collections/hashmap.rs
  foyer-intrusive/src/collections/mod.rs
  foyer-intrusive/src/core/adapter.rs
  foyer-intrusive/src/dlist.rs
  foyer-intrusive/src/eviction/fifo.rs
  foyer-intrusive/src/eviction/lfu.rs
  foyer-intrusive/src/eviction/lru.rs
  foyer-intrusive/src/eviction/mod.rs
  foyer-intrusive/src/eviction/sfifo.rs
  foyer-intrusive/src/lib.rs
  foyer-memory/src/eviction/fifo.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/lru.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/lib.rs
  foyer-memory/src/prelude.rs
  foyer-memory/src/queue/generic.rs
  foyer-memory/src/queue/mod.rs
Labels: refactor

#350 feat: introduce `CacheBuilder` for in-memory cache
  examples/memory.rs
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/prelude.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/storage.rs
  foyer-storage/tests/storage_test.rs
Labels: feature, refactor

#353 chore: enable rust backtrace for nextest
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
Labels: chore, test

#354 feat: introduce fs device config builder to auto detect config
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-common/Cargo.toml
  foyer-common/src/fs.rs
  foyer-common/src/lib.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/storage.rs
  foyer-storage/tests/storage_test.rs
  foyer-workspace-hack/Cargo.toml
Labels: feature, refactor

#358 feat: introduce unified store, store write, store config
  foyer-storage-bench/src/main.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/none.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
Labels: feature, refactor

#363 refactor: loose query key bound for foyer-storage
  foyer-common/src/code.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/none.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
Labels: refactor

#366 feat: use serde to ser/de storage key and value
  .gitignore
  .typos.toml
  foyer-common/Cargo.toml
  foyer-common/src/code.rs
  foyer-storage-bench/Cargo.toml
  foyer-storage-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_ticket.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/none.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/reinsertion/exist.rs
  foyer-storage/src/reinsertion/mod.rs
  foyer-storage/src/reinsertion/rated_ticket.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
  foyer-workspace-hack/Cargo.toml
Labels: feature, refactor

#369 feat: introduce store builder for disk cache for simplification
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
Labels: feature, refactor

#371 refactor: remove `Clone` bound for storage key and value
  foyer-common/Cargo.toml
  foyer-common/src/arc_key_hash_map.rs
  foyer-common/src/code.rs
  foyer-common/src/lib.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_ticket.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/judge.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/none.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/reinsertion/exist.rs
  foyer-storage/src/reinsertion/mod.rs
  foyer-storage/src/reinsertion/rated_ticket.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
  foyer-storage/tests/storage_test.rs
  foyer-workspace-hack/Cargo.toml
Labels: feature, refactor

#374 fix: fix build on apple silicon
  foyer-storage/src/buffer.rs
Labels: bug

#375 fix: call syncfs when fs device flush on macos
  foyer-storage/src/device/fs.rs
Labels: bug

#377 chore: update readme
  README.md
Labels: chore

#379 feat: introduce weighter for in-memory cache
  examples/memory.rs
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage/src/region_manager.rs
Labels: feature, refactor

#380 fix: assert handle weight and refactor handle
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/fifo.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/lru.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/handle.rs
  foyer-memory/src/listener.rs
Labels: bug

#384 perf: load each entry with at most one request
  foyer-storage/src/device/mod.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/region.rs
Labels: refactor, perf

#386 test: add warm up for foyer-storage-bench, use ahash to hash catalog
  foyer-storage-bench/src/analyze.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/catalog.rs
Labels: test

#387 chore: remove debug bound for storage key value
  foyer-common/src/code.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_ticket.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region_manager.rs
  foyer-storage/src/reinsertion/mod.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
Labels: chore

#391 feat: unify foyer in-memory cache and disk cache
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  etc/grafana/dashboards/foyer.json
  examples/Cargo.toml
  examples/hybrid.rs
  examples/memory.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/prelude.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/indices.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/metrics.rs
  foyer-storage/src/none.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/reinsertion/exist.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/Cargo.toml
  foyer/src/hybrid.rs
  foyer/src/lib.rs
  foyer/src/prelude.rs
Labels: feature, refactor

#392 chore: fix example
  examples/hybrid.rs
Labels: chore, test

#393 refacor: refactor clone bound
  foyer-common/src/code.rs
  foyer/src/hybrid.rs
Labels: refactor

#396 refactor: use Arcable for foyer-storage
  foyer-common/src/arcable.rs
  foyer-common/src/lib.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/none.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
Labels: refactor

#397 refactor: use Arc<K> Arc<V> for in-memory cache handle
  foyer-common/src/arc_key_hash_map.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/indexer.rs
  foyer-memory/src/listener.rs
  foyer/src/hybrid.rs
Labels: refactor

#398 refactor: remove some clone bound
  examples/hybrid.rs
  examples/memory.rs
  foyer-common/src/arc_key_hash_map.rs
  foyer-common/src/arcable.rs
  foyer-common/src/lib.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/indexer.rs
  foyer-storage/src/admission/mod.rs
  foyer-storage/src/admission/rated_ticket.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/none.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/reinsertion/exist.rs
  foyer-storage/src/reinsertion/mod.rs
  foyer-storage/src/reinsertion/rated_ticket.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
  foyer/src/hybrid.rs
  foyer/src/prelude.rs
Labels: refactor

#399 refactor: remove clone bound from entry()
  foyer-storage/src/catalog.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/none.rs
  foyer-storage/src/runtime.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid.rs
Labels: refactor

#400 feat: add ghost queue for s3fifo, fix panic
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/s3fifo.rs
Labels: bug, feature, refactor

#401 chore: fix config check, update examples, README, CI
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  README.md
  examples/Cargo.toml
  examples/hybrid.rs
  examples/hybrid_full.rs
  foyer-intrusive/README.md
  foyer-storage/src/generic.rs
  foyer-storage/src/store.rs
Labels: documentation, chore, refactor

#402 chore: release foyer v0.8
  CHANGELOG.md
  foyer-common/Cargo.toml
  foyer-experimental-bench/Cargo.toml
  foyer-experimental/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-workspace-hack/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#404 chore: tiny refactor on rated ticket test args
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-common/src/rated_ticket.rs
Labels: chore, test

#405 feat: flush device after close storage
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  foyer-storage/src/generic.rs
Labels: feature

#407 feat: add config to control flush for io
  README.md
  examples/hybrid_full.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer-workspace-hack/Cargo.toml
  foyer/src/hybrid.rs
Labels: bug, feature

#408 chore: release foyer v0.8.1
  CHANGELOG.md
  README.md
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-workspace-hack/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#409 fix: fix build with night feature
  .config/hakari.toml
  foyer-storage/Cargo.toml
  foyer-storage/src/lib.rs
  foyer-workspace-hack/Cargo.toml
  foyer/Cargo.toml
  foyer/src/lib.rs
Labels: bug

#410 chore: relase foyer v0.8.2
  CHANGELOG.md
  README.md
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-workspace-hack/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#412 refactor: expose code traits
  foyer/src/lib.rs
  foyer/src/prelude.rs
Labels: refactor

#413 chore: release foyer v0.8.3
  CHANGELOG.md
  foyer/Cargo.toml
Labels: chore

#415 refactor: expose hybrid cache entry
  foyer/src/prelude.rs
Labels: refactor

#416 chore: relase foyer v0.8.4
  CHANGELOG.md
  foyer/Cargo.toml
Labels: chore

#417 refactor: add default random state for hybrid entry
  foyer/src/hybrid.rs
Labels: refactor

#418 refactor: expose entry state
  foyer/src/prelude.rs
Labels: refactor

#420 refactor: loose entry args trait bound
  foyer/src/hybrid.rs
Labels: refactor

#421 refactor: expose storage writer
  foyer/src/prelude.rs
Labels: refactor

#422 refactor: export metrics related components
  foyer/src/prelude.rs
Labels: refactor

#423 refactor: expose RangeBoundsExt, BufExt and BufMutExt
  foyer/src/prelude.rs
Labels: refactor

#424 chore: release foyer v0.8.5
  CHANGELOG.md
  foyer/Cargo.toml
Labels: chore

#425 chore: upgrade ci actions
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  foyer-experimental/Cargo.toml
  foyer-experimental/src/wal.rs
Labels: chore

#427 refactor: remove hakari
  .config/hakari.toml
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Cargo.toml
  Makefile
  README.md
  foyer-common/Cargo.toml
  foyer-experimental-bench/Cargo.toml
  foyer-experimental/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer-workspace-hack/.gitattributes
  foyer-workspace-hack/Cargo.toml
  foyer-workspace-hack/build.rs
  foyer-workspace-hack/src/lib.rs
  foyer/Cargo.toml
  scripts/install-deps.sh
Labels: refactor

#428 chore: remove unused dependencies, add udeps ci
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  Makefile
  foyer-common/Cargo.toml
  foyer-experimental-bench/Cargo.toml
  foyer-experimental/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore, dependencies

#429 chore: release foyer v0.8.6
  CHANGELOG.md
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#430 fix: fix `freespace()` on non-exist path
  foyer-storage/src/device/fs.rs
Labels: bug

#431 chore: release foyer-storage v0.7.4
  CHANGELOG.md
  foyer-storage/Cargo.toml
Labels: chore

#432 fix: fix the ghost queue bug with s3fifo
  foyer-memory/Cargo.toml
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/eviction/s3fifo.rs
Labels: bug

#434 chore: release foyer-memory v0.3.4
  CHANGELOG.md
  foyer-memory/Cargo.toml
Labels: chore

#435 refactor: impl Clone for hybrid cache
  foyer/src/hybrid.rs
Labels: refactor

#436 chore: release foyer 0.8.7
  CHANGELOG.md
  foyer/Cargo.toml
Labels: chore

#441 feat: impl Default, serde for eviction configs, impl debug for hybrid
  Cargo.toml
  foyer-common/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/fifo.rs
  foyer-memory/src/eviction/lfu.rs
  foyer-memory/src/eviction/lru.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/eviction/s3fifo.rs
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/src/hybrid.rs
Labels: feature

#442 chore: release foyer v0.8.8
  CHANGELOG.md
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#444 feat: introduce recover mode
  README.md
  examples/hybrid_full.rs
  foyer-storage/src/catalog.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/storage.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/hybrid.rs
  foyer/src/prelude.rs
Labels: feature

#445 refactor: restore bound map with cfg
  foyer-common/Cargo.toml
  foyer-common/src/range.rs
Labels: refactor

#446 feat: add config to enable/disable direct io
  README.md
  examples/hybrid_full.rs
  foyer-storage-bench/src/main.rs
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/fs.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lazy.rs
  foyer-storage/src/reclaimer.rs
  foyer-storage/src/region.rs
  foyer-storage/src/storage.rs
  foyer-storage/tests/storage_test.rs
Labels: feature, refactor

#448 chore: release foyer v0.8.9
  CHANGELOG.md
  foyer-common/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage-bench/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#450 chore: remove some uncessary deps
  foyer-storage/Cargo.toml
  foyer-storage/src/device/fs.rs
Labels: dependencies

#453 refactor: extract key value serde code to serde mod
  foyer-storage/src/buffer.rs
  foyer-storage/src/device/allocator.rs
  foyer-storage/src/error.rs
  foyer-storage/src/flusher.rs
  foyer-storage/src/generic.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/serde.rs
Labels: refactor
