Repository foyer-rs/foyer, pull requests merged in 2024-07, with the labels that each got.

#589 refactor: rename TraceConfig to TracingConfig, udpate related API
  docker-compose.yaml
  foyer-bench/src/main.rs
  foyer-common/src/lib.rs
  foyer-common/src/tracing.rs
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: refactor

#590 doc: add tail-based tracing example, update readme
  .github/template/template.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .typos.toml
  Cargo.toml
  Makefile
  README.md
  examples/Cargo.toml
  examples/tail_based_tracing.rs
Labels: documentation

#591 fix: insert disk cache on hybrid cache fetch miss
  foyer-storage/src/large/generic.rs
  foyer/Cargo.toml
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: bug

#592 refactor: fetch no longer requires returned value with context
  README.md
  examples/hybrid_full.rs
  foyer-bench/src/main.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer/Cargo.toml
  foyer/src/hybrid/cache.rs
Labels: refactor

#594 refactor: remove atomic op in #591
  foyer-common/src/future.rs
  foyer-common/src/lib.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-memory/src/prelude.rs
  foyer/src/hybrid/cache.rs
Labels: refactor

#595 chore: release foyer 0.10.0
  CHANGELOG.md
  README.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#597 refactor: refine storage write model
  foyer-common/src/lib.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/mod.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-util/Cargo.toml
  foyer-util/src/async_batch_pipeline.rs
  foyer-util/src/lib.rs
Labels: refactor, perf

#598 feat: add disk cache flush buffer threshold
  README.md
  examples/hybrid_full.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/store/mod.rs
  foyer-storage/src/store/runtime.rs
  foyer/src/hybrid/builder.rs
Labels: feature

#599 chore: release foyer 0.10.1
  CHANGELOG.md
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-intrusive/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#602 refactor: separate store and storage abstraction
  foyer-storage/src/device/allocator.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/mod.rs
  foyer-storage/src/picker/utils.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_test.rs
  foyer/src/hybrid/cache.rs
  foyer/src/hybrid/writer.rs
Labels: refactor

#604 chore: remove some unused
  foyer-common/src/event.rs
  foyer-util/src/judge.rs
Labels: chore

#605 feat: combined disk cache framework (p2)
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/region.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer-storage/src/tombstone.rs
  foyer/src/prelude.rs
Labels: feature, refactor

#606 refactor: make statistics sharable between engines
  foyer-storage/src/large/generic.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
Labels: refactor

#608 feat: write temp buffer before engine enqueue
  foyer-storage/src/engine.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
Labels: feature, refactor

#609 feat: refine either storage
  foyer-common/src/future.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/writer.rs
  foyer/src/prelude.rs
Labels: feature, refactor

#610 feat: make large object disk cache use the high region ids
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
Labels: feature, refactor

#611 feat: introduce load order for either storage
  foyer-storage/src/prelude.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/store.rs
Labels: feature

#613 refactor: further separate large object disk cache components
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/indexer.rs
  foyer-storage/src/large/mod.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/large/serde.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/store.rs
Labels: refactor

#612 feat: introduce compact bloom filter
  foyer-common/Cargo.toml
  foyer-common/src/compact_bloom_filter.rs
  foyer-common/src/lib.rs
Labels: feature

#614 feat: introduce 4K-aligned IoBytes and IoBytesMut
  foyer-storage/src/device/allocator.rs
  foyer-storage/src/device/bytes.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/engine.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/region.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/storage/mod.rs
  foyer-storage/src/storage/noop.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
Labels: feature

#615 feat: introduce async wait group
  foyer-common/src/lib.rs
  foyer-common/src/wait_group.rs
Labels: feature

#617 chore: add chroma to the showcase
  README.md
Labels: chore

#618 chore: rename minitrace to fastrace
  Cargo.toml
  examples/Cargo.toml
  examples/tail_based_tracing.rs
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
  foyer-common/Cargo.toml
  foyer-common/src/tracing.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/cache.rs
  foyer-memory/src/generic.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/indexer.rs
  foyer/Cargo.toml
  foyer/src/hybrid/cache.rs
Labels: chore, dependencies

#619 refactor: parallel write buffer writing for large object disk cache
  foyer-common/src/metrics.rs
  foyer-common/src/wait_group.rs
  foyer-storage/src/device/bytes.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/indexer.rs
  foyer-storage/src/large/mod.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/storage/runtime.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/builder.rs
Labels: feature, refactor, perf

#623 chore: fix a rust docs
  foyer-storage/src/store.rs
Labels: documentation, chore
