Repository foyer-rs/foyer, pull requests merged in 2025-07, with the labels that each got.

#1041 feat: implement SIEVE eviction policy for foyer-memory
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/mod.rs
  foyer-memory/src/eviction/sieve.rs
  foyer-memory/src/raw.rs
Labels: feature

#1049 build: replace makefile ecosystem with cargo x-task eco
  .cargo/config.toml
  .github/workflows/ci.yml
  Cargo.toml
  Makefile
  codecov.yml
  etc/grafana/dashboards/foyer.json
  etc/grafana/dashboards/node-exporter-full.json
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
  scripts/install-deps.sh
  scripts/minimize-dashboards.sh
  scripts/monitor.sh
  xtask/Cargo.toml
  xtask/src/main.rs
Labels: test

#1052 refactor: remove unnecessary and misleading `with_flush()` API
  README.md
  examples/hybrid_full.rs
  foyer-bench/src/main.rs
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/device/test_utils.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/tombstone.rs
  foyer-storage/src/region.rs
  foyer-storage/src/small/generic.rs
  foyer-storage/src/small/set_manager.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_fuzzy_test.rs
  foyer/src/hybrid/builder.rs
Labels: refactor

#1053 chore: fix some tiny typos
  foyer-storage/src/picker/utils.rs
Labels: chore

#1054 fix: fix delete by recording tombstones in lodc indexer
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/indexer.rs
  foyer-storage/src/large/reclaimer.rs
Labels: bug

#1056 feat: impl auto close for hybrid cache
  foyer/src/hybrid/cache.rs
Labels: feature

#1068 chore: remove unreferenced files
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/device/monitor.rs
  foyer-storage/src/device/test_utils.rs
Labels: chore

#1069 refactor: reorg modules
  foyer-storage/src/engine/large/engine.rs
  foyer-storage/src/engine/large/eviction.rs
  foyer-storage/src/engine/large/flusher.rs
  foyer-storage/src/engine/large/mod.rs
  foyer-storage/src/engine/large/reclaimer.rs
  foyer-storage/src/engine/large/recover.rs
  foyer-storage/src/engine/large/region.rs
  foyer-storage/src/engine/large/scanner.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/picker/mod.rs
  foyer-storage/src/picker/utils.rs
  foyer-storage/src/prelude.rs
Labels: refactor

#1070 refactor: introduce parition abstrction to device
  examples/hybrid_full.rs
  foyer-bench/src/main.rs
  foyer-storage/src/engine/large/engine.rs
  foyer-storage/src/engine/large/eviction.rs
  foyer-storage/src/engine/large/flusher.rs
  foyer-storage/src/engine/large/indexer.rs
  foyer-storage/src/engine/large/reclaimer.rs
  foyer-storage/src/engine/large/recover.rs
  foyer-storage/src/engine/large/region.rs
  foyer-storage/src/engine/large/scanner.rs
  foyer-storage/src/engine/large/tombstone.rs
  foyer-storage/src/io/device/combined.rs
  foyer-storage/src/io/device/file.rs
  foyer-storage/src/io/device/fs.rs
  foyer-storage/src/io/device/mod.rs
  foyer-storage/src/io/device/noop.rs
  foyer-storage/src/io/device/partial.rs
  foyer-storage/src/io/engine/mod.rs
  foyer-storage/src/io/engine/monitor.rs
  foyer-storage/src/io/engine/noop.rs
  foyer-storage/src/io/engine/psync.rs
  foyer-storage/src/io/engine/uring.rs
  foyer-storage/src/io/error.rs
  foyer-storage/src/prelude.rs
  foyer-storage/src/store.rs
  foyer-storage/tests/storage_fuzzy_test.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: refactor

#1072 feat: add iopoll for uring io engine and more tunable args
  foyer-bench/src/main.rs
  foyer-storage/src/engine/large/engine.rs
  foyer-storage/src/io/engine/uring.rs
Labels: feature

#1076 feat: add more tuning args for uring engine
  Cargo.toml
  foyer-bench/src/main.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/io/engine/uring.rs
Labels: feature

#1079 test: support adding latency for cache miss in foyer-bench
  examples/Cargo.toml
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
Labels: test

#1080 feat: introduce keeper to make disk cache write queue queryable
  foyer-memory/src/cache.rs
  foyer-memory/src/pipe.rs
  foyer-memory/src/prelude.rs
  foyer-memory/src/raw.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/engine/large/engine.rs
  foyer-storage/src/engine/large/flusher.rs
  foyer-storage/src/engine/mod.rs
  foyer-storage/src/engine/noop.rs
  foyer-storage/src/keeper.rs
  foyer-storage/src/lib.rs
  foyer-storage/src/store.rs
  foyer/src/hybrid/cache.rs
Labels: feature

#1083 refactor: remove device dependency in io engine
  foyer-storage/src/engine/large/engine.rs
  foyer-storage/src/engine/large/eviction.rs
  foyer-storage/src/engine/large/region.rs
  foyer-storage/src/engine/large/scanner.rs
  foyer-storage/src/engine/large/tombstone.rs
  foyer-storage/src/engine/mod.rs
  foyer-storage/src/io/engine/mod.rs
  foyer-storage/src/io/engine/monitor.rs
  foyer-storage/src/io/engine/noop.rs
  foyer-storage/src/io/engine/psync.rs
  foyer-storage/src/io/engine/uring.rs
  foyer-storage/src/store.rs
Labels: refactor
