Repository foyer-rs/foyer, pull requests merged in 2025-03, with the labels that each got.

#871 perf: reuse inflight buf in lodc to reduce alloc and page fault
  foyer-storage/src/io/mod.rs
  foyer-storage/src/large/flusher.rs
Labels: perf

#872 refactor: clear some todos and fixmes
  .github/workflows/ci.yml
  Makefile
  foyer-bench/Cargo.toml
  foyer-common/src/bits.rs
  foyer-common/src/range.rs
  foyer-memory/Cargo.toml
  foyer-memory/src/raw.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/device/mod.rs
  foyer-storage/src/large/flusher.rs
  foyer/Cargo.toml
Labels: chore, refactor

#880 fix: drop useless mut
  foyer-common/src/tracing.rs
  foyer/src/hybrid/cache.rs
Labels: refactor

#881 feat: support continuous blob write, write ASAP
  foyer-bench/src/main.rs
  foyer-common/src/metrics.rs
  foyer-storage/src/io/mod.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/buffer.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/indexer.rs
  foyer-storage/src/large/mod.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/recover.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/batch.rs
  foyer-storage/src/small/set.rs
  foyer-storage/src/store.rs
Labels: feature, refactor

#883 refactor: remove stale functions, refine error
  foyer-storage/src/large/generic.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/batch.rs
  foyer-storage/src/small/set.rs
Labels: refactor

#885 feat: add disk cache load error metrics
  foyer-common/src/metrics.rs
  foyer-storage/src/small/generic.rs
Labels: feature

#886 fix: fix missed load error metrics
  README.md
  foyer-storage/src/large/generic.rs
Labels: bug

#887 feat: add metrics to measure lodc buffer efficiency
  etc/grafana/dashboards/foyer.json
  foyer-common/src/metrics.rs
  foyer-storage/src/large/buffer.rs
  foyer-storage/src/large/flusher.rs
Labels: feature

#892 chore: upgrade deps
  Cargo.toml
  examples/Cargo.toml
  foyer-bench/Cargo.toml
  foyer-cli/Cargo.toml
  foyer-common/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: chore

#895 feat: enhance histogram precieseness, fix ser histogram
  Cargo.toml
  foyer-common/src/metrics.rs
  foyer-storage/src/large/buffer.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/small/batch.rs
Labels: feature

#893 chore: release foyer v0.15.0
  CHANGELOG.md
  Cargo.toml
  README.md
Labels: chore

#900 feat: support either writer disk cache on eviction or on insertion
  .github/workflows/ci.yml
  Cargo.toml
  foyer-bench/src/main.rs
  foyer/Cargo.toml
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
  foyer/src/prelude.rs
Labels: feature

#901 chore: release foyer v0.15.1
  CHANGELOG.md
  Cargo.toml
Labels: chore

#904 test: separate rust test and foyer bench test but merge codecov
  .github/workflows/ci.yml
Labels: test

#906 refactor: mitigate low-pri errors, refine errors
  foyer-storage/src/device/direct_file.rs
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/error.rs
  foyer-storage/src/large/generic.rs
Labels: refactor

#907 chore: release foyer v0.15.2
  CHANGELOG.md
  Cargo.toml
Labels: chore

#912 fix: fix split condition calculation error
  foyer-storage/src/device/direct_fs.rs
  foyer-storage/src/large/buffer.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
Labels: bug

#914 chore: release foyer v0.15.3
  CHANGELOG.md
  Cargo.toml
Labels: chore

#921 refactor: replace verbose channel overflow warn log with metrics
  foyer-common/src/metrics.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/generic.rs
  foyer-storage/src/small/flusher.rs
Labels: refactor
