Repository foyer-rs/foyer, pull requests merged in 2025-02, with the labels that each got.

#854 refactor(deps): adopt rand 0.9
  Cargo.toml
  examples/Cargo.toml
  foyer-bench/Cargo.toml
  foyer-bench/src/main.rs
  foyer-cli/Cargo.toml
  foyer-common/Cargo.toml
  foyer-common/src/asyncify.rs
  foyer-common/src/rate.rs
  foyer-common/src/rated_ticket.rs
  foyer-common/src/runtime.rs
  foyer-memory/Cargo.toml
  foyer-memory/benches/bench_dynamic_dispatch.rs
  foyer-memory/benches/bench_hit_ratio.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/raw.rs
  foyer-storage/Cargo.toml
  foyer-storage/src/region.rs
  foyer-storage/src/storage/either.rs
  foyer-storage/src/store.rs
  foyer/Cargo.toml
Labels: dependencies, refactor

#856 deps: switch between tokio impls with cfg(madsim)
  Cargo.toml
  foyer-bench/Cargo.toml
  foyer-common/Cargo.toml
  foyer-memory/Cargo.toml
  foyer-storage/Cargo.toml
  foyer/Cargo.toml
Labels: dependencies, refactor

#857 chore: release foyer v0.14.1
  CHANGELOG.md
  Cargo.toml
Labels: chore

#865 refactor: remove unnecessary piece holder in batch
  .github/workflows/ci.yml
  foyer-common/src/runtime.rs
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/batch.rs
  foyer-storage/src/small/flusher.rs
  foyer-storage/src/small/set.rs
  foyer-storage/src/small/set_manager.rs
Labels: refactor

#867 refactor: use key hash for pickers to minimise reinsertion overhead
  foyer-storage/src/large/generic.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/picker/mod.rs
  foyer-storage/src/picker/utils.rs
  foyer-storage/src/store.rs
  foyer-storage/src/test_utils.rs
  foyer-storage/tests/storage_fuzzy_test.rs
  foyer/src/hybrid/builder.rs
  foyer/src/hybrid/cache.rs
  foyer/src/hybrid/writer.rs
Labels: refactor

#869 refactor: refine kv serde
  foyer-storage/src/large/batch.rs
  foyer-storage/src/large/flusher.rs
  foyer-storage/src/large/reclaimer.rs
  foyer-storage/src/large/scanner.rs
  foyer-storage/src/serde.rs
  foyer-storage/src/small/batch.rs
  foyer-storage/src/small/set.rs
  foyer-storage/src/small/set_manager.rs
Labels: refactor
