Repository foyer-rs/foyer, pull requests merged in 2025-09, with the labels that each got.

#1114 fix: fix is_noop() logic in store.rs (#1113)
  foyer-storage/src/store.rs
Labels: bug

#1115 chore: release foyer v0.19.2
  CHANGELOG.md
  Cargo.toml
Labels: chore

#1126 fix: fix foyer website logo
  Cargo.toml
  README.md
  foyer/src/lib.rs
  website/docs/01-overview/index.md
  website/src/pages/index.tsx
Labels: bug, documentation

#1123 fix: fix ephemeral entry becomes ephemeral after access
  examples/event_listener.rs
  foyer-common/src/properties.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/test_utils.rs
  foyer-memory/src/raw.rs
  foyer-memory/src/record.rs
  foyer/src/hybrid/cache.rs
  foyer/src/hybrid/writer.rs
Labels: bug

#1132 docs: update arch docs
  website/docs/05-design/01-architecture.md
  website/docs/05-design/assets/cache.svg
  website/docs/05-design/assets/hybrid-cache-compatible-mode.svg
  website/docs/05-design/assets/hybrid-cache.svg
Labels: documentation

#1133 chore: update npm dependencies version
  website/package-lock.json
Labels: documentation, dependencies

#1136 docs: update case study - RisingWave
  website/docs/05-case-study/01-risingwave/assets/compaction.svg
  website/docs/05-case-study/01-risingwave/assets/lsm-tree.svg
  website/docs/05-case-study/01-risingwave/assets/refill-comparison.png
  website/docs/05-case-study/01-risingwave/assets/refill.svg
  website/docs/05-case-study/01-risingwave/assets/working-set-foyer.svg
  website/docs/05-case-study/01-risingwave/assets/working-set.svg
  website/docs/05-case-study/01-risingwave/index.md
Labels: documentation

#1137 docs: update case study - RisingWave
  website/docs/05-case-study/01-risingwave/assets/block-size.svg
  website/docs/05-case-study/01-risingwave/assets/huge-disk-cache.svg
  website/docs/05-case-study/01-risingwave/index.md
Labels: documentation

#1146 docs: add arch and case study docs link in readme
  README.md
  website/docs/01-overview/index.md
  website/docs/02-getting-started/01-in-memory-cache.md
  website/docs/02-getting-started/02-hybrid-cache.md
  website/docs/02-getting-started/03-monitor/assets/metrics.png
  website/docs/02-getting-started/03-monitor/index.md
  website/docs/02-getting-started/_category_.json
  website/docusaurus.config.ts
  website/sidebars.ts
Labels: documentation

#1147 fix: fix issue 1121 panics on concurrent disk cache write & fetch
  foyer-common/src/properties.rs
  foyer-memory/src/cache.rs
  foyer-memory/src/eviction/test_utils.rs
  foyer-memory/src/raw.rs
  foyer/Cargo.toml
  foyer/src/hybrid/cache.rs
  foyer/src/hybrid/writer.rs
  foyer/tests/hybrid_cache_fuzzy_test.rs
Labels: bug, refactor

#1161 test: separate read and fetch in hybrid cache fuzzy test
  foyer/tests/hybrid_cache_fuzzy_test.rs
Labels: test

#1163 fix: removed unnecessary constraints to allow use of non-static keys
  foyer-storage/src/store.rs
  foyer/src/hybrid/cache.rs
Labels: refactor
